# Generated by Django 5.2.4 on 2025-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewbella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('user', models.CharField(blank=True, max_length=100)),
                ('productname', models.CharField(blank=True, max_length=100)),
                ('proprice', models.IntegerField(blank=True)),
                ('productquantity', models.IntegerField(blank=True)),
                ('total', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordername', models.CharField(max_length=100)),
                ('phoneno', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('tamount', models.IntegerField()),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('ispaid', models.BooleanField(default=False)),
                ('razorpay_payment_id', models.CharField(max_length=100)),
            ],
        ),
    ]
